### ISSUE TITLE
 Conform to PEP 420

### ISSUE THREAD

**Issue by FRidh** [chrippa/backports.shutil_get_terminal_size#13]
backports is a namespace package, however, it has a init.py which is conforming the rejected PEP 382. PEP 420, which is final, states that

> Namespace packages cannot contain an init.py

- PEP 420 specification: https://www.python.org/dev/peps/pep-0420/#specification
- PEP 382: https://www.python.org/dev/peps/pep-0382/
- Discussion where we encountered this issue: https://github.com/NixOS/nixpkgs/issues/22319
- Issue for `backports.ssl_match_hostname`

**Comment by RonnyPfannschmidt** [comment]
@FRidh pep420 doesn't apply to python2.7 - this is setuptools namespaces that need the file

**Comment by FRidh** [comment]
Indeed, closing.
